name: Run tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          cli: 1.11.1.1149
          # clj-kondo: 2022.05.31

      - name: Run tests
        run: clojure -M:test:run-tests
