name: Run tests
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pathom_ver: [2, 3]
    steps:
      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: '1.11.1.1208'
          # clj-kondo: 2022.05.31

      - name: Run tests
        run: clojure -M:pathom${{ matrix.pathom_ver }}:test:run-tests
